config/routes.rb
Rails.application.routes.draw do
 
 root 'pages#home'
  
 get '/home', to: 'pages#home'
 
 resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  
 
end

app/views/pages/home.html.erb
<div class="center jumbotron">
  <div class="well">
  <h1>Welcome to My Recipes App</h1>
  <h2>There are delicious recipes here!
  <br>Create a free account and share yours today!</h2>
  </div>
  <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-danger" %>
</div>
  
  <div class="row">
    <div class = "col-lg-4">
      <h3 class="midrow">
        View Recipes as Guest User
      </h3>
      <h2 class="left">Browse and view recipes as a guest and sign up later.</h2>
      <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
    </div>
    
    <div class = "col-lg-4">
      <h3 class="midrow">
        Sign In To Your Account
      </h3>
      <h2 class="left">Add/Update your recipes/Create reviews/like-dislike recipes and much more!</h2>
      <p><%= link_to "Log in to your account", login_path, class: "btn btn-warning btn-small" %></p>
    </div>
    
    <div class = "col-lg-4">
      <h3 class="midrow">
        Watch a Funny Dog Video
      </h3>
      <h2 class="left">Not hungry after all? Click here to watch funny videos of dogs instead.</h2>
      <p><%= link_to "Funny Dog Videos", "https://youtu.be/GF60Iuh643I", class: "btn btn-warning btn-small" %></p>
    </div>
    
  </div>